import { Permission, Role } from '@prisma/client';

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [Role.SUPER_ADMIN]: [
    Permission.LEADS_VIEW,
    Permission.LEADS_CREATE,
    Permission.LEADS_ASSIGN,
    Permission.QUOTES_VIEW,
    Permission.QUOTES_CREATE,
    Permission.APPLICATIONS_VIEW,
    Permission.APPLICATIONS_UPDATE,
    Permission.DOCUMENTS_VIEW,
    Permission.DOCUMENTS_UPLOAD,
    Permission.PAYMENTS_VIEW,
    Permission.POLICIES_VIEW,
    Permission.POLICIES_ISSUE,
    Permission.COMMISSIONS_VIEW,
    Permission.COMMISSIONS_RECONCILE,
    Permission.INSURERS_MANAGE,
    Permission.PRODUCTS_MANAGE,
    Permission.USERS_MANAGE,
    Permission.AUDIT_VIEW,
  ],
  [Role.ADMIN]: [
    Permission.LEADS_VIEW,
    Permission.LEADS_CREATE,
    Permission.LEADS_ASSIGN,
    Permission.QUOTES_VIEW,
    Permission.QUOTES_CREATE,
    Permission.APPLICATIONS_VIEW,
    Permission.APPLICATIONS_UPDATE,
    Permission.DOCUMENTS_VIEW,
    Permission.DOCUMENTS_UPLOAD,
    Permission.PAYMENTS_VIEW,
    Permission.POLICIES_VIEW,
    Permission.POLICIES_ISSUE,
    Permission.COMMISSIONS_VIEW,
    Permission.COMMISSIONS_RECONCILE,
    Permission.INSURERS_MANAGE,
    Permission.PRODUCTS_MANAGE,
    Permission.USERS_MANAGE,
    Permission.AUDIT_VIEW,
  ],
  [Role.OPERATIONS]: [
    Permission.LEADS_VIEW,
    Permission.LEADS_CREATE,
    Permission.LEADS_ASSIGN,
    Permission.QUOTES_VIEW,
    Permission.QUOTES_CREATE,
    Permission.APPLICATIONS_VIEW,
    Permission.APPLICATIONS_UPDATE,
    Permission.DOCUMENTS_VIEW,
    Permission.DOCUMENTS_UPLOAD,
    Permission.PAYMENTS_VIEW,
    Permission.POLICIES_VIEW,
    Permission.POLICIES_ISSUE,
  ],
  [Role.SALES]: [
    Permission.LEADS_VIEW,
    Permission.LEADS_CREATE,
    Permission.LEADS_ASSIGN,
    Permission.QUOTES_VIEW,
    Permission.QUOTES_CREATE,
    Permission.APPLICATIONS_VIEW,
  ],
  [Role.CUSTOMER_SUPPORT]: [
    Permission.LEADS_VIEW,
    Permission.QUOTES_VIEW,
    Permission.APPLICATIONS_VIEW,
    Permission.APPLICATIONS_UPDATE,
    Permission.DOCUMENTS_VIEW,
    Permission.DOCUMENTS_UPLOAD,
    Permission.POLICIES_VIEW,
  ],
  [Role.FINANCE]: [
    Permission.PAYMENTS_VIEW,
    Permission.POLICIES_VIEW,
    Permission.COMMISSIONS_VIEW,
    Permission.COMMISSIONS_RECONCILE,
  ],
  [Role.PARTNER]: [
    Permission.LEADS_VIEW,
    Permission.QUOTES_VIEW,
    Permission.APPLICATIONS_VIEW,
    Permission.POLICIES_VIEW,
  ],
  [Role.CUSTOMER]: [
    Permission.QUOTES_VIEW,
    Permission.QUOTES_CREATE,
    Permission.APPLICATIONS_VIEW,
    Permission.DOCUMENTS_VIEW,
    Permission.DOCUMENTS_UPLOAD,
    Permission.POLICIES_VIEW,
  ],
};
